expensetracker/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView
from . import views

app_name = 'expensetracker'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^expenses/$', login_required(views.ExpensesView.as_view()), name='expenses'),
    url(r'^add_expense/$', views.add_expense, name='add_expense'),
    #url(r'^.*', RedirectView.as_view(url='/expensetracker/', permanent=False), name='index'),
    #url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

finplan/urls.py
from django.conf.urls import include, url, patterns
from django.http import HttpResponseRedirect
from django.contrib import admin
from rest_framework import routers
from expensetracker import views
from django.conf import settings

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'expenses', views.ExpensesViewSet)
router.register(r'categories', views.CategoriesViewSet)

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('expensetracker/')),
    url(r'^expensetracker/api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^polls/', include('polls.urls')),
    url(r'^expensetracker/', include('expensetracker.urls')),
    url(r'^admin/', admin.site.urls),
]

# if settings.DEBUG:
#     urlpatterns += patterns(
#         'django.views.static',
#         (r'media/(?P<path>.*)',
#         'serve',
#         {'document_root': settings.MEDIA_ROOT}), )

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

expensetracker/forms.py
from .models import UserProfile, Category, Expense
from django.contrib.auth.models import User
from django import forms
from django.utils import timezone

class UserForm(forms.ModelForm):
    username = forms.CharField(help_text="Please enter a username.")
    email = forms.CharField(help_text="Please enter your email.")
    password = forms.CharField(widget=forms.PasswordInput(), help_text="Please enter a password.")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(help_text="Please enter your website.", required=False)

    class Meta:
        model = UserProfile
        fields = ['website']

class ExpenseForm(forms.ModelForm):
    summary = forms.CharField(help_text="Please enter transaction summary.")
    amount = forms.DecimalField(decimal_places=2, max_digits=15, help_text="Please enter transaction amount.")
    transaction_date = forms.DateField(widget=forms.SelectDateWidget, help_text="Please enter transaction date", initial=timezone.now())
    category = forms.ModelChoiceField(Category.objects.all(), help_text="Please select a category")

    class Meta:
        model = Expense
        fields = ['summary', 'amount', 'transaction_date', 'category']

expensetracker/views.py
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, render
from django.template import RequestContext
from rest_framework import viewsets

from .serializers import UserSerializer, GroupSerializer, ExpenseSerializer, CategorySerializer
from .forms import UserForm, UserProfileForm, ExpenseForm
from .models import Expense, Category

def index(request):
    context = RequestContext(request)

    return render_to_response("expensetracker/index.html", {}, context)

def register(request):
    # Like before, get the request's context.
    context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print (user_form.errors, profile_form.errors)

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render_to_response(
            'expensetracker/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
            context)

def user_login(request):
    # Like before, obtain the context for the user's request.
    context = RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/expensetracker/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print
            "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('expensetracker/login.html', {}, context)

# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/expensetracker/')

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer

class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

class ExpensesViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows expenses to be viewed or edited.
    """
    queryset = Expense.objects.all()
    serializer_class = ExpenseSerializer

class CategoriesViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows categories to be viewed or edited.
    """
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class ExpensesView(generic.ListView):
    template_name = 'expensetracker/expenses.html'
    context_object_name = 'all_expenses'

    def get_queryset(self):
        return Expense.objects.all().order_by('transaction_date')

@login_required
def add_expense(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect('/expensetracker/expenses/')
        else:
            print
            form.errors
    else:
        form = ExpenseForm

    return render(request, 'expensetracker/add_expense.html', {'form': form})

expensetracker/templates/expensetracker/add_expense.html
{% extends 'expensetracker/base.html' %}

{% block title %}Homepage{% endblock %}

{% block body_block %}

<div class="hero-unit">
    <h1>Add an Expense</h1>

    <div class="container">
        <form class="span6" id="category_form" method="post" action="{% url 'expensetracker:add_expense' %}">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
            {% endfor %}

           <input class="btn btn-primary" type="submit" name="submit" value="Create Expense"/>
        </form>
    </div>
</div>

{% endblock %}

expensetracker/templates/expensetracker/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap -->
        <link href="{% static 'expensetracker/css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
        <link href="{% static 'expensetracker/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'expensetracker/css/bootstrap-responsive.css' %}" rel="stylesheet">
        <title>FinPlan - {% block title %}{{"Financial Planning at its best!"}}{% endblock %}</title>
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
           <div class="navbar-inner">
               <div class="container">
                   <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                   </button>
                   <a class="brand" href="/expensetracker/">Expense Tracker</a>

                   <div class="nav-collapse collapse">
                       <ul class="nav pull-right">
                           {% if user.is_authenticated %}
                            <li class="navbar-text">Welcome, {{ user.username }}!</li>
                            <li><a href="{% url 'expensetracker:logout' %}">Logout</a></li>
                           {% else %}
                            <li><a href="{% url 'expensetracker:register' %}">Register Here</a></li>
                            <li><a href="{% url 'expensetracker:login' %}">Login</a></li>
                           {% endif %}
                       </ul>
                       <ul class="nav">
                           {% if user.is_authenticated %}
                            <li><a href="/admin/">Administration</a></br></li>
                            <li><a href="/expensetracker/api/">API</a></br></li>
                            <li><a href="{% url 'expensetracker:expenses' %}">Expenses</a></li>
                            <li><a href="{% url 'expensetracker:add_expense' %}">Add Expense</a></li>
                           {% endif %}
                       </ul>
                   </div>
                    <!--/.nav-collapse -->
               </div>
           </div>
        </div>

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span3">
                    <div class="well sidebar-nav">
                        <!--- Empty for the timebeing -->
                    </div>
                    <!--/.well -->
                </div>
                <!--/span-->
                <div class="span9">
                    {% block body_block %}
                    {% endblock %}
                </div>
                <!--/span-->
            </div>
            <!--/row-->
        </div>
        <!--/.fluid-container-->

        <hr>

        <footer>
            <div class="container">
                <p>&copy; FinPlan: Financial Planning Platform 2016</p>
            </div>
        </footer>

        <script src="{% static 'expensetracker/js/jquery-3.0.0.min.js' %}"></script>
        <script src="{% static 'expensetracker/js/bootstrap.min.js' %}"></script>
    </body>
</html>

expensetracker/templates/expensetracker/details.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

expensetracker/templates/expensetracker/expenses.html
{% extends 'expensetracker/base.html' %}

{% load staticfiles %}

{% block title %}Expenses{% endblock %}

{% block body_block %}

<div class="hero-unit">
{% if all_expenses %}
    <table class="table table-bordered table-striped">
        <tr>
            <th>Date</th>
            <th>Summary</th>
            <th>Amount</th>
            <th>Category</th>
        </tr>
    {% for expense in all_expenses %}
        <tr>
            <td>{{expense.transaction_date}}</td>
            <td>{{expense.summary}}</td>
            <td>{{expense.amount}}</td>
            <td>
                {% for c in expense.category.all %}
                {{ c.name }}
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No expenses are available.</p>
{% endif %}
</div>
{% endblock %}

expensetracker/templates/expensetracker/index.html
{% extends 'expensetracker/base.html' %}

{% block title %}Homepage{% endblock %}

{% block body_block %}
<div class="hero-unit">
    {% if user.is_authenticated %}
        <h1>Hello {{user.username}}</h1>
    {% else %}
        <h1>Hello! Please login..</h1>
    {% endif %}
</div>
{% endblock %}

expensetracker/templates/expensetracker/login.html
{% extends 'expensetracker/base.html' %}

{% block title %}Login{% endblock %}

{% block body_block %}

<div class="hero-unit">
    <h1>Login to Expense Tracker</h1>

    <div class="container">
        <form class="form-signin span4" id="login_form" method="post" action="{% url 'expensetracker:login' %}">
            <h2 class="form-signin-heading">Please sign in</h2>
            {% csrf_token %}

            {% if bad_details %}
                <p><strong>Your username and/or password were incorrect!</strong></p>
            {% elif disabled_account %}
                <p><strong>Your account is currently disabled; we can't log you in!</strong></p>
            {% endif %}

            Username: <input type="text" class="input-block-level" placeholder="Username" name="username" value="" size="50" />
            <br />
            Password: <input type="password" class="input-block-level" placeholder="Password" name="password" value="" size="50" />
            <br />

            <input class="btn btn-primary" type="submit" value="submit" />
        </form>
    </div>
</div>
{% endblock %}

expensetracker/templates/expensetracker/register.html
{% extends 'expensetracker/base.html' %}

{% block title %}Registration{% endblock %}

{% block body_block %}
<div class="hero-unit">
    <h1>Register with Expense Tracker</h1>
    <br />

    <div class="container">
        {% if registered %}
            <p>Thank you for registering!</p>

            <p><a href="{% url 'expensetracker:index' %}">Return to the homepage.</a></p>
        {% else %}
            <form id="user_form" class="form-signin span8" method="post" action="{% url 'expensetracker:register' %}"
                    enctype="multipart/form-data">

                {% csrf_token %}
                <h2 class="form-signin-heading">Sign up Here</h2>
                <!-- Display each form. The as_p method wraps each element in a paragraph
                     (<p>) element. This ensures each element appears on a new line,
                     making everything look neater. -->
                {% for field in user_form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                {% endfor %}

                {% for field in profile_form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                {% endfor %}

                <br />
                <!-- Provide a button to click to submit the form. -->
                <input class="btn btn-primary" type="submit" name="submit" value="Register"/>
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}

expensetracker/templates/expensetracker/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>